loadedInterfaceName = "notes with tilt / offset for velocity";

interfaceOrientation = "portrait";

whRatio = 2 / 3;

shouldUseTilt = true;

infoText = "This interface is a simple scripting demo showing a couple of ways you can manipulate MIDI note velocities. When the interface first loads the value of the accelerometer x-axis is used to determine the velocity for the left button; the y-axis is used to determine the velocity of the right button. If the offset button is pressed, the offset of the touch position will be used instead of tilt. For the left button, the xOffset will be used. This means that the further to the right of the button your touch is, the higher the velocity will be. For the right button, the inverse of the yOffset is used... the closer to the top of the button your touch is the higher the velocity value will be.<br><br> The buttons output to cc 7 and 8 for MIDI, and /left and /right for OSC destinations.<br><br>NOTE: if you have a device with a gyro sensor it would be better to use the gyro and core motion to determine tilt as it yields more accurate tilt values than the accelerometer alone.";

pages = [[
{
    "name": "left",
    "type": "Button",
    "x": 0,
    "y": 0,
    "width": .5,
    "height": .6,
    "startingValue": 0,
    "color": "#055",
    "stroke": "#aaaaaa",
    "min": 0,
    "max": 127,
    "mode": "momentary",
    "protocol": "MIDI",
    "midiType": "noteon",
    "midiNumber": 7,
    "address": "/left",
    "requiresTouchDown": true,
    "onvaluechange": "if(shouldUseTilt) { this.value = Math.round(this.value * acc.x);  } else { this.value = Math.round(this.value * this.xOffset);  } leftLabel.setValue(this.value);",
},
{
    "name": "leftLabel",
    "type": "Label",
	"size": "20px",
    "x": 0,
    "y": 0,
    "width": .5,
    "height": .6,
	"value":"",
},

{
    "name": "right",
    "type": "Button",
    "x": .5,
    "y": 0,
    "width": .49,
    "height": .6,
    "startingValue": 0,
    "color": "#555555",
    "stroke": "#aaaaaa",
    "min": 0,
    "max": 127,
    "mode": "momentary",
    "protocol": "MIDI",
    "midiType": "noteon",
    "midiNumber": 8,
    "address": "/right",
    "requiresTouchDown": true,
    "onvaluechange": "if(shouldUseTilt) { this.value = Math.round(this.value * acc.y); } else { this.value = 127 - Math.round(this.value * this.yOffset); } rightLabel.setValue(this.value);	",
},
{
    "name": "rightLabel",
    "type": "Label",
	"size": "20px",
    "x": .5,
    "y": 0,
    "width": .49,
    "height": .6,
	"value": "",
},
{
    "name": "tabButton",
    "type": "Button",
    "x": .8,
    "y": .85,
    "width": .19,
    "height": .15 * whRatio,
    "mode": "toggle",
    "color": "#333",
    "stroke": "#aaa",
    "isLocal": true,
    "ontouchstart": "if(this.value == this.max) { control.showToolbar(); } else { control.hideToolbar(); }",
},

{
    "name": "tabLabel",
    "type": "Label",
    "x": .8,
    "y": .85,
    "width": .19,
    "height": .15 * whRatio,
    "mode": "contact",
    "isLocal": true,
    "value": "menu",
},

{
    "name": "velocityLabel",
    "type": "Label",
    "x": .0,
    "y": .6,
    "width": .75,
    "height": .15 * whRatio,
	"align":"left",
    "value": "velocity is determined by : tilt",
},

{
    "name": "tiltButton",
    "type": "Button",
    "x": .0,
    "y": .685,
    "width": .5,
    "height": .15 * whRatio,
    "mode": "contact",
    "color": "#333333",
    "stroke": "#aaaaaa",
    "midiType": "noteon",
    "isLocal": true,
    "ontouchstart": "shouldUseTilt = true; velocityLabel.setValue(\'velocity is determined by : tilt\')",
},

{
    "name": "tiltLabel",
    "type": "Label",
    "x": .0,
    "y": .685,
    "width": .5,
    "height": .15 * whRatio,
	"value": "TILT",
},

{
    "name": "offsetButton",
    "type": "Button",
    "x": .5,
    "y": .685,
    "width": .49,
    "height": .15 * whRatio,
    "mode": "contact",
    "color": "#333333",
    "stroke": "#aaaaaa",
    "midiType": "noteon",
    "isLocal": true,
    "ontouchstart": "shouldUseTilt = false; velocityLabel.setValue(\'velocity is determined by : xOffset / yOffset\')",
},
{
    "name": "offsetButton",
    "type": "Label",
    "x": .5,
    "y": .685,
    "width": .49,
    "height": .15 * whRatio,
	"value": "OFFSET",
},
{
    "name": "infoButton",
    "type": "Button",
    "x": .6,
    "y": .85,
    "width": .2,
    "height": .15 * whRatio,
    "mode": "contact",
    "color": "#333333",
    "stroke": "#aaaaaa",
    "midiType": "noteon",
    "isLocal": true,
    "ontouchstart": "control.changePage(1);",
},
{
    "name": "infoButtonLabel",
    "type": "Label",
    "x": .6,
    "y": .85,
    "width": .2,
    "height": .15 * whRatio,
    "color": "#fff",
    "value": "info",
},

{
    "name": "acc",
    "type": "Accelerometer",
    "isLocal": true,
    "min": 0,
    "max": 1
},

],

[
{
    "name": "infoText",
    "type": "Label",
    "x": .1,
    "y": .1,
    "width": .8,
    "height": .7,
    "value": infoText,
    "verticalCenter": false,
    "align": "left",
},
{
    "name": "backButton",
    "type": "Button",
    "x": .8,
    "y": .9,
    "width": .19,
    "height": .09,
    "mode": "contact",
    "color": "#333333",
    "stroke": "#aaaaaa",
    "isLocal": true,
    "ontouchstart": "control.changePage(0);",
},
{
    "name": "infoButtonLabel",
    "type": "Label",
    "x": .8,
    "y": .9,
    "width": .19,
    "height": .09,
    "color": "#fff",
    "value": "back",
},

],

];